# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('owner', "Do'kon egasi"), ('cashier', 'Kassir')], default='cashier', max_length=10),
        ),
    ]
