# Generated by Django 5.2.17 on 2026-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('owner', "Do'kon egasi"), ('cashier', 'Kassir')], default='cashier', max_length=16),
        ),
    ]
