# Generated by Django 5.2.17 on 2026-08-18 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Kirish'), ('login_blocked', 'Kirish bloklandi'), ('logout', 'Chiqish'), ('admin_revoked_device', 'Qurilma chiqarildi'), ('admin_unblocked_device', 'Qurilmaga ruxsat berildi'), ('revoke_all', 'Barcha qurilmalar chiqarildi')], max_length=32)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_audits_as_actor', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_audits_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='accounts_de_target__4aca03_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('browser_version', models.CharField(blank=True, max_length=32)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('refresh_jti', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('revoked', 'Chiqarilgan'), ('expired', 'Muddati tugagan'), ('allowed', 'Ruxsat berilgan')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_de_user_id_520a07_idx'), models.Index(fields=['user', 'device_id'], name='accounts_de_user_id_edad7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('browser_version', models.CharField(blank=True, max_length=32)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Muvaffaqiyatli kirish'), ('blocked', 'Rad etilgan'), ('logout', 'Chiqish')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_lo_user_id_b22310_idx')],
            },
        ),
    ]
