# Generated by Django 5.2.17 on 2026-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deviceauditlog_devicesession_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicesession',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='deviceauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Kirish'), ('login_blocked', 'Kirish bloklandi'), ('logout', 'Chiqish'), ('admin_revoked_device', 'Qurilma chiqarildi'), ('admin_unblocked_device', 'Qurilmaga ruxsat berildi'), ('admin_edited_device', "Qurilma ma'lumotlari tahrirlandi"), ('revoke_all', 'Barcha qurilmalar chiqarildi')], max_length=32),
        ),
    ]
