# Generated by Django 5.2.17 on 2026-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_device_device_sessions_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('revoked', 'Chiqarilgan'), ('expired', 'Muddati tugagan')], default='active', max_length=16),
        ),
    ]
