# Generated by Django 5.2.17 on 2026-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rebuild_informational_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
