# Generated by Django 5.2.17 on 2026-08-25 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_device_is_removed_device_removed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('sale', 'Savdo'), ('debt', 'Qarz'), ('device', 'Qurilma'), ('application', 'Ariza'), ('system', 'Tizim')], db_index=True, default='system', max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notif_user_read_idx')],
            },
        ),
    ]
