# Generated by Django 5.2.17 on 2026-08-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('shops', '0009_storeapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodePriceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_memories', to='shops.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'barcode'), name='catalog_bpm_shop_barcode_uniq')],
            },
        ),
    ]
