# Generated by Django 5.2.17 on 2026-08-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_storeapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_merchant_id', models.CharField(blank=True, max_length=64)),
                ('payme_card', models.CharField(blank=True, max_length=32)),
                ('click_service_id', models.CharField(blank=True, max_length=64)),
                ('click_merchant_id', models.CharField(blank=True, max_length=64)),
                ('click_card', models.CharField(blank=True, max_length=32)),
                ('paynet_merchant_id', models.CharField(blank=True, max_length=64)),
                ('paynet_card', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shops.shop')),
            ],
        ),
    ]
