# Generated by Django 5.2.17 on 2026-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='qr_card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='qr_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
