# Generated by Django 5.2.17 on 2026-08-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shopsettings_qr_card_number_shopsettings_qr_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Yopilgan (deaktiv) do'kon egasi kira olmaydi, ma'lumotlari arxiv sifatida saqlanadi."),
        ),
    ]
