# Generated by Django 5.2.17 on 2026-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('paynet', 'Paynet'), ('visa', 'Visa'), ('nasiya', 'Nasiya')], default='cash', max_length=20),
        ),
    ]
