# Generated by Django 6.1 on 2026-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
