# Generated by Django 5.2.17 on 2026-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('xarid', '🛒 Xarid'), ('ijara', '🏠 Ijara'), ('kommunal', '💡 Kommunal'), ('transport', '🚗 Transport'), ('maosh', '👥 Maosh'), ('yetkazish', '📦 Yetkazib berish'), ('reklama', '📣 Reklama'), ('boshqa', '🧾 Boshqa')], db_index=True, default='xarid', max_length=16),
        ),
    ]
