# Generated by Django 5.2.17 on 2026-08-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='period',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
