# Generated by Django 5.2.17 on 2026-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_expense_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ijara', 'Ijara'), ('kommunal', 'Kommunal'), ('ish_haqi', 'Ish haqi'), ('tovar', 'Tovar / Yetkazib beruvchi'), ('transport', 'Transport'), ('tamirlash', "Ta'mirlash"), ('boshqa', 'Boshqa')], db_index=True, default='boshqa', max_length=16),
        ),
    ]
