# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('step', models.CharField(blank=True, max_length=40)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('store_name', models.CharField(blank=True, max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
