# Generated by Django 5.2.17 on 2026-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('completed', 'Yakunlandi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='botsession',
            name='app_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='botsession',
            name='app_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='botsession',
            name='app_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='botsession',
            name='app_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='botsession',
            name='app_stage',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
