# Generated by Django 5.2.17 on 2026-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_supportapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='form_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='botsession',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='botsession',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='botsession',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
